### ISSUE TITLE
[Question] About the pcap's in latest release

### ISSUE THREAD

**Issue by favna** [yellows8/3ds_smashbroshax#1]
Hey Yellows8,
The latest release have the pcap's for *hax2.5, but I was just wondering if the eurdemo pcap from that is **_also**_ updated for 2.5? This being because whenever I try to run smashbroshax now my smash does "crash" sorta... but always just gets stuck on [static top screens](http://i.imgur.com/G3KLoeU.jpg) (it's either this or a bunch of grey/white lines). I have triple checked the payload I use which most definitely is New3DS 10.2.0-28E downloaded just today, same goes for the boot.3dsx. The root of my SD card is as seen [here](http://i.imgur.com/y3nskOa.png) (the extra files are because I just copy+pasted them from my o3DS)

To send the packets I have followed Cydget's video and all-in-one batch file from [this GBATemp thread](https://gbatemp.net/threads/tutorial-using-smashhax-with-linux.397194/page-4#post-5772968)

At any rate, I wouldn't be surprised if it's just the demo being the issue, but i'd like to hear from you if you can tell me more. 

Lastly a small list to recap on what I have/use:
- Ubuntu 15.10 as OS
- Linksys WUSB54GC as WiFi USB Dongle (build in card is incompatible)
- New3DSXL with firmware 10.2.0-28E
- Smash Infinite Use Demo - European region

**Comment by yellows8** [comment]
"a bunch of grey/white lines" Can you get a pic of that?

All of the pcaps are supposed to be built with latest git, so all of them should support payload 2.5.

**Comment by favna** [comment]
That would be [this](http://i.imgur.com/c9ERD08.jpg). 

Also Cydget has reported on the [GBATemp thread](https://gbatemp.net/threads/tutorial-using-smashhax-with-linux.397194/page-5#post-5774629) that the US demo also doesn't work (I would assume he meant it gives the same "error")

**Comment by yellows8** [comment]
Will have to debug this myself I guess, haven't tested with the demo in a long while.

**Comment by yellows8** [comment]
Oh wow I forgot that the smash-demo doesn't have SD access, ugh.....

**Comment by yellows8** [comment]
With the demo your only option is to build it yourself with the PAYLOADURL option.

**Comment by favna** [comment]
Well.. Guess i better do some extra research on how exactly to do that then. Thanks for assessing the issue :)!
