### ISSUE TITLE
not a issue, but I may of found something

### ISSUE THREAD

**Issue by Reual4412** [yellows8/3ds_smashbroshax#11]
ok I already had my 3ds hacked with homemenu hax, for my old 3ds, Interestingly enough though is if I click the homemenu button the game freezes and I have to shut it down manually. that is not the main thing, the thing is my 3ds (old 3ds) acts as if it was trying to load homebrew (obviously unsuccessful and no colors) in the latest version. I believe there is a chance that a homebrew launcher for old 3ds is now possible, I don't know If you could implement this, I'll tell what I was doing before the froze. playing classic, homemenu button press game froze. Of course the multiplayer option cannot be used but classic potentially. latest update as of 2/6/2016

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/13
