### ISSUE TITLE
Smash bros crashes but homebrew launcher doesn't launch

### ISSUE THREAD

**Issue by aaronson2012** [yellows8/3ds_smashbroshax#15]
My new 3ds is on version 10.7
And smash is on ver 1.0.1 from the eshop

The top screen will go garbled and the music will keep playing but homebrew launcher wont launch

I have the correct payload and am using the 1.0.1 pcap

Any advice?

Thanks

**Comment by Shadowxp13** [comment]
Hey, can you please send me the 1.0.1 pcap, i'm in the same firmware and have 1.0.1 from eshop too.
I can test it for you.

**Comment by aaronson2012** [comment]
Yeah just give me an hour or so I'll upload it.

**Comment by Shadowxp13** [comment]
Thanks!

**Comment by aaronson2012** [comment]
Hey sorry it took me so long, here is the 1.0.1 pcap compiled with the 10.7 payload

https://onedrive.live.com/redir?resid=A30F7E100D513D7D!10426&authkey=!APMBS-n9nXFQTNs&ithint=file%2cpcap

please tell me if it works for you!

**Comment by Shadowxp13** [comment]
Wow, thanks. i'll reboot into Ubuntu and will test this.
I'll post the results after testing!

**Comment by Shadowxp13** [comment]
First try resulted in nothing, testing again

**Comment by aaronson2012** [comment]
Did the game crash for you but not boot into homebrew launcher?

**Comment by Shadowxp13** [comment]
Yep

**Comment by aaronson2012** [comment]
Okay, hopefully the author will fix this, thanks for testing it for me

**Comment by Shadowxp13** [comment]
Yeah, how did you compiled the payload, can it be a writing error or something in the payload path?
Just thinking about it.

**Comment by aaronson2012** [comment]
I did everything as per this guide. https://www.youtube.com/watch?v=8RUfuc0DHHg

It was compiled using this command:
make "PAYLOADPATH=../smashpayload.bin"
the payload file was up one level in my file structure

I downloaded the payload from https://smealum.github.io/3ds/
Putting in NEW 10 7 0 32 U in the dropdown boxes.

Just so we're on the same page

**Comment by aaronson2012** [comment]
Okay i may have made a mistake let me try compiling again. be right back

**Comment by aaronson2012** [comment]
Okay I am an idiot. I misunderstood the compiling process. I though PAYLOADPATH refered to the  path to the payload on the computer.

HERE is the working pcap for 1.0.1 https://onedrive.live.com/redir?resid=A30F7E100D513D7D!10427&authkey=!AE_QvKI6-RIaBQE&ithint=file%2cpcap

**Comment by aaronson2012** [comment]
This issue can be closed now.

**Comment by warchicken** [comment]
Will it work on n3ds 10.7u with physical game cartridge deleting updates
and now in v1.0.1(USA) , i have tried but the packets stop at 73,
