### ISSUE TITLE
System rebooting after catching the packet.

### ISSUE THREAD

**Issue by miguelgfreitas** [yellows8/3ds_smashbroshax#21]
Hi, I'm trying to do this method with a 1.1.0 physical copy of smash. I'm running 10.7 FW.

Every time I've tried to launch the homebrew, the new 3ds just crashes and reboots. Could you take a look at a packet to see if it looks right? I've started over sometimes and I always get the same result.

**Comment by yellows8** [comment]
What region?

EDIT: FWIW it worked fine for me when I originally added support for it(tested with USA).

**Comment by miguelgfreitas** [comment]
I'm using the EU game, and the '110other' files.

**Comment by griryu** [comment]
I am also using the EU version of the game (Physical Copy), the version number is also 1.1.0 and i am running FW 10.7. I have tried this multiple times and the game just goes back to the home menu after running it. I will be trying another laptop later today so hopefully its just my own laptop that is affecting it. I'll let you know how it goes.

**Comment by yellows8** [comment]
FWIW I don't really know why it's supposedly "broken", but remember it doesn't work right _all_ the time either.

**Comment by miguelgfreitas** [comment]
I've tried 5 or 6 times, it detects the Beacon in less than 3 seconds. 

Should I keep trying, or just give up? 

Also, I don't know if this is worth mentioning, but I had to delete smash's extra data on the SD for it to return to its original version. Is that relevant in any way?

**Comment by yellows8** [comment]
"Is that relevant in any way? " Shouldn't be.

**Comment by yellows8** [comment]
#17
