### ISSUE TITLE
USA 1.1.0 Cartridge, New3DS 10.7.0.32U - Crashing back to system menu and rebooting.

### ISSUE THREAD

**Issue by Flagers** [yellows8/3ds_smashbroshax#22]
Hi, whenever I try to use SmashBrosHax to homebrew my New3DS 10.7.0.32U. I have tried 50+ times and come to the same result. I predict that this is happening because of the offsets. You used an eShop version to make the pcap for the USA 1.1.0. Could you try making a cartridge version.

**Comment by yellows8** [comment]
#13
