### ISSUE TITLE
1.0.1 freezes when entering Group 

### ISSUE THREAD

**Issue by Gamma624** [yellows8/3ds_smashbroshax#28]
Hi, I'm using a N3ds running software version 11.0 U and 1.0.1 US pcap for smashhax. when i entered all the specified commands the packets sent fine (No stopping at 93 packets) but when i entered group chat I would either be greeted by gray lines or a mesh of different colors on screen, without successfully booting into the hbl. I'm currently running on Ubuntu 16.04 if that makes a difference. Maybe it's my wireless card? any help would be appreciated, Thanks!

**Comment by yellows8** [comment]
" either be greeted by gray lines or a mesh of different colors on screen," That's not really specific enough.

**Comment by Gamma624** [comment]
Heres two pics. 

(https://cloud.githubusercontent.com/assets/20617069/17080216/d9bf508e-50f4-11e6-8ca4-2bd5daed8451.JPG)

(https://cloud.githubusercontent.com/assets/20617069/17080214/bc979af2-50f4-11e6-8b79-5ecf49b7317f.JPG)
When I enter group the game almost instantly freezes then the top screen displays either one of those images. I also deleted my update data to get to v 1.0.1 on my system if that has to do with anything. Sorry if you cannot view the images, I'm pretty new to Github and don't really know a ton. If they don't show up I can upload them to a different website.

**Comment by yellows8** [comment]
Sounds like you didn't setup the SD payload file as described in the README properly.

**Comment by Gamma624** [comment]
I'll go check that out now, thanks :)

**Comment by Gamma624** [comment]
Seems fine to me. I put my smashpayload.bin folder to the root of my sd card and directed my devkitARM there.

**Comment by yellows8** [comment]
"directed my devkitARM there." Huh?

**Comment by Gamma624** [comment]
sorry, made payloadpath=smashpayload.bin

**Comment by yellows8** [comment]
"PAYLOADPATH=/smashpayload.bin"

**Comment by Gamma624** [comment]
Thats what I put in terminal I just didn't say it properly here XD

**Comment by yellows8** [comment]
So does anything happen after the top-screen framebuffer is overwritten, or does it just hang?

**Comment by Gamma624** [comment]
Nothing happens, just hangs

**Comment by yellows8** [comment]
What's the exact build command you used?

**Comment by Gamma624** [comment]
the build command to compile smashhax?

**Comment by yellows8** [comment]
Yes.

**Comment by Gamma624** [comment]
I first ran export DEVKITARM=~/Desktop/devkitpro/devkitARM (I didn't make it in my ops or use a perl script to create devkitpro) 
then ran make "PAYLOADPATH=/smashpayload.bin" and it compiled fine.

**Comment by Gamma624** [comment]
opt\* not ops sorry

**Comment by yellows8** [comment]
Dunno.

**Comment by Gamma624** [comment]
Alright, I'm gonna guess it's just my wireless card. I really appreciate you helping me out, Thank you :)

EDIT-just saw that browser/menuhax was re-released for 11.0, Thanks you very much for saving me money on a new wireless card Yellows!

**Comment by ieattheworld** [comment]
hi yellow, Im having some problems with smashbroshax. To begin with I have a N3DSXL 11.0.0.33u with a smash bros 1.1.0 version. I did every step fine up to the part where the packages are sent. My smash bros just closes and says error, any idea why?
