### ISSUE TITLE
SmashHax Demo

### ISSUE THREAD

**Issue by Valkart** [yellows8/3ds_smashbroshax#3]
Hello, how do I build the pcap to be able to use the hax on the demo? I barely manage using Ubuntu and I want to learn on how to do it. Thanks in advance and thank you for the hax,

**Comment by Cydget** [comment]
This isnt really an issue so you might want to close it. You need to install devkitpro and its counterparts(http://3dbrew.org/wiki/Setting_up_Development_Environment) and follow the readme in the git
