### ISSUE TITLE
V1.1.0 and Firmware 11.2.0-35E

### ISSUE THREAD

**Issue by NoobleMcScrunchkin** [yellows8/3ds_smashbroshax#32]
When using a cartridge with 1.1.0 loaded onto it , and using no other downloaded content/updates, I have found that using smashbroshax has been unsuccessful although it says that it is supported and tested.

> v1.0.0. USA: supported+tested. "gameother": supported+tested.
> v1.0.1. USA: supported+tested.
> v1.0.2. USA: supported, not tested.
> v1.0.4. USA: supported+tested. "gameother": supported, not tested.
> v1.0.5. USA: "supported". The target heap address for overwriting the target object varies, hence this hax doesn't actually work right with this version. This version is not fully supported due to this.
> v1.1.0. USA: supported+tested. **"gameother": supported+tested.**
> v1.1.1. USA: supported+tested. "gameother": supported+tested.
> v1.1.2. USA: supported+tested. "gameother": supported+tested.

I would like to get this to work as i am hoping to be able to use this to install basehax and eventually downgrade to 9.2. 
Is there a possibility of this being fixed in the future?

**Comment by yellows8** [comment]
"a cartridge with 1.1.0 loaded onto it" The README specifically mentions updates included with the title itself...

**Comment by NoobleMcScrunchkin** [comment]
oh i missed that
