### ISSUE TITLE
The homemenu ropbin is ready.

### ISSUE THREAD

**Issue by Riven-Spell** [yellows8/3ds_smashbroshax#34]
I'm attempting smashhax on the game version usa 1.0.0 and a new 3ds on version 11.2.0.0-35U and I reach the black screen with text that says "The homemenu ropbin is ready". I've loaded starter.zip as well as the otherapp payload, but it still crashes.

Any ideas?

**Comment by yellows8** [comment]
Wrong \*hax payload.
