### ISSUE TITLE
Menu ropbin is ready crash

### ISSUE THREAD

**Issue by walrus227** [yellows8/3ds_smashbroshax#5]
I'm on an Old 3ds with 10.3.0-28U firmware. I have the correct otherapp on the root of my sd card renamed to smashpayload.bin . When I go to group, the payload launches and gets to "menu ropbin is ready", then crashes to the home screen.

Is Smashhax even compatible with old 3ds? Or just new? Please help.

**Comment by yellows8** [comment]
"Is Smashhax even compatible with old 3ds? Or just new? Please help." README
